import type { NextRequest } from "next/server";
import fs from "fs";
import path from "path";
import { REGIONS, type RegionCode } from "@/lib/types";

/**
 * GET /api/metrics?region=ERCO
 *
 * Serves model evaluation metrics generated by data/train.py.
 */
export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const region = (searchParams.get("region") ?? "ERCO").toUpperCase() as RegionCode;

  if (!(region in REGIONS)) {
    return Response.json(
      { error: `Unknown region: ${region}. Valid: ${Object.keys(REGIONS).join(", ")}` },
      { status: 400 }
    );
  }

  const metricsPath = path.resolve(process.cwd(), "data", "models", `${region}_metrics.json`);
  const altPath = path.resolve(process.cwd(), "..", "data", "models", `${region}_metrics.json`);
  const filePath = fs.existsSync(metricsPath) ? metricsPath : altPath;

  if (!fs.existsSync(filePath)) {
    return Response.json(
      { error: `No metrics available for ${region}. Run: python data/train.py --region ${region}` },
      { status: 404 }
    );
  }

  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    const metrics = JSON.parse(raw);
    return Response.json(metrics);
  } catch (err) {
    console.error("Metrics read error:", err);
    return Response.json(
      { error: "Failed to read metrics data" },
      { status: 500 }
    );
  }
}
