import type { NextRequest } from "next/server";
import fs from "fs";
import path from "path";
import { REGIONS, type RegionCode } from "@/lib/types";

/**
 * GET /api/forecast?region=ERCO
 *
 * Serves pre-computed forecast JSON generated by data/train.py.
 * No model inference at request time — just a file read.
 */
export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const region = (searchParams.get("region") ?? "ERCO").toUpperCase() as RegionCode;

  if (!(region in REGIONS)) {
    return Response.json(
      { error: `Unknown region: ${region}. Valid: ${Object.keys(REGIONS).join(", ")}` },
      { status: 400 }
    );
  }

  // Resolve forecast file path
  const forecastPath = path.resolve(process.cwd(), "data", "models", `${region}_forecast.json`);
  const altPath = path.resolve(process.cwd(), "..", "data", "models", `${region}_forecast.json`);
  const filePath = fs.existsSync(forecastPath) ? forecastPath : altPath;

  if (!fs.existsSync(filePath)) {
    return Response.json(
      { error: `No forecast available for ${region}. Run: python data/train.py --region ${region}` },
      { status: 404 }
    );
  }

  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    const forecast = JSON.parse(raw);
    return Response.json(forecast);
  } catch (err) {
    console.error("Forecast read error:", err);
    return Response.json(
      { error: "Failed to read forecast data" },
      { status: 500 }
    );
  }
}
